spring.application.name=ewaste-pickup
spring.datasource.url=jdbc:mysql://localhost:3306/ewaste_pickup
spring.datasource.username=root
spring.datasource.password=rahulshetye1234@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true